### ISSUE TITLE
amqp connection access problems

### ISSUE THREAD

**Issue by fractalcat** [anchor/ceilometer-publisher-zeromq#16]
This is sometimes getting raised by the Ceilometer notification agent when running with AMQP as the messaging backend:

```
2015-02-13 05:31:53.136 18370 ERROR ceilometer.pipeline [-] Pipeline meter_sink: Continue after error from publisher <ceilometer_publisher_rabbitmq.queue.QueuePublisher object at 0x2639f50>
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline Traceback (most recent call last):
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/ceilometer/pipeline.py", line 304, in _publish_samples
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     p.publish_samples(ctxt, transformed_samples)
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/ceilometer_publisher_rabbitmq/queue.py", line 88, in publish_samples
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     while not self.publish_sample(message):
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/ceilometer_publisher_rabbitmq/queue.py", line 74, in publish_sample
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     routing_key='',
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/kombu/entity.py", line 251, in publish
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     immediate=immediate)
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/amqp/channel.py", line 2130, in basic_publish_confirm
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     self.wait([(60, 80)])
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     self.channel_id, allowed_methods)
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 237, in _wait_method
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     self.method_reader.read_method()
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline     raise m
2015-02-13 05:31:53.136 18370 TRACE ceilometer.pipeline RuntimeError: Second simultaneous read on fileno 6 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of GreenThread object at 0x246b690>; THAT THREAD=FdListener('read', 6, <built-in method switch of GreenThread object at 0x246b4b0>, <built-in method throw of GreenThread object at 0x246b4b0>)
```

My working hypothesis is that it's sharing a connection context with the code in Ceilometer which reads from the oslo messaging layer. Currently verifying.

**Comment by fractalcat** [comment]
Workaround put in place in #17. The workaround sucks because it sacrifices write confirmation from RabbitMQ; no guarantee that samples actually get written. Leaving this open until we have a solution that doesn't have this problem. 

One option I've explored is rewriting the publisher to use `oslo.messaging` rather than using `kombu` directly; `oslo.messaging` comes with some baggage (different message format, additional bits of information needed, et cetera), and there may (or may not) be a way to solve this while still using `kombu`. 

(CC @barneydesmond)

**Comment by olorin** [comment]
No longer relevant.
